apiVersion: v2
name: mi-microservicio
description: Chart de Helm para desplegar el microservicio en Kubernetes
type: application

# version: del chart (subir si cambian templates o values)
version: 0.1.0

# appVersion: version de la app — mas informativo, no tiene que coincidir con el tag Docker
appVersion: "1.0.0"
